namespace :MyApp do
  require 'Rk/cbuilder'

  # Setup a builder for our module
  b = CBuilder.new 'MyApp', 'c'

  # A simple list of source files
  #
  sources = [ 'main.c', 'util.c' ]
  objs = []
  exe = b.distdir("MyApp#{b.exeext}")

  # Create file rules to compile each to an object file.
  # Also build a list of those object files for easy use as a prerequisite.
  #
  for s in sources do
    objs.push(b.obj_file(s))
  end


  task :default => [ :build, :link ]

  # build task depends on the object files
  #
  multitask :build => objs

  # Link the object files into a shared library
  #
  task :link => [ :build, exe ]

  file exe => objs do
    b.make_executable exe, objs, ['libfoo', 'MyLib']
  end

  CLOBBER.include exe

end
